### ISSUE TITLE
Don’t publish environment files to version control

### ISSUE THREAD

**Issue by syropian** [Mijago/D2ArmorPicker#43]
You're exposing all of your credentials to the world 😬

**Comment by Mijago** [comment]
Do you mean the API Keys?

**Comment by noodleWrecker7** [comment]
The main issue is the client_secret, it's the equivalent of a password and shouldn't be exposed. If you're using a client secret for the authorization code flow then the authorization logic should be run on a server away from the client so that the client secret is never exposed.
In the case of this app, its run entirely in the users client which means you don't need a server, but it does mean that you should be using the implicit grant flow for authorization. 
There is a little more info [here](https://auth0.com/docs/authorization/flows/implicit-flow-with-form-post)
I'd be happy to help you out further with this if you want

**Comment by aronhoyer** [comment]
As a side note, I'd recommend you to setup a way for people to submit security issues that's not GitHub issues, @Mijago. Having security issues publicly accessible as GitHub issues is, in itself, a security issue.

Ditto for reporting security issues.
