### ISSUE TITLE
Eye of another world hidden stats

### ISSUE THREAD

**Issue by Adamsdown-Boy** [Mijago/D2ArmorPicker#54]
Hi there - great tool (just bought a few coffees). I think the Warlock Eye of Another World helmet has a hidden +30 to Recovery, Discipline and Strength, that can push stat effects beyond 100, which could be useful to take into account.

**Comment by Mijago** [comment]
This could be useful, but only as a toggle-switch in the advanced settings - otherwise it could lead to confusion.
There are many more exotics with hidden intrinsic stats. It would be a great help if you could search for a detailed list of them, as well as the conditions, then I can make a draft for it :)

**Comment by Mijago** [comment]
Closed in favor of https://github.com/Mijago/D2ArmorPicker/issues/106
